### ISSUE TITLE
二维码解析错误

### ISSUE THREAD

**Issue by caoxiaoyu** [jaguarsy/HBHelper#1]
<img width="447" alt="bug" src="https://user-images.githubusercontent.com/17612109/40159966-27d63c6c-59de-11e8-85d9-4b8522a3ae29.png">

二维码是sso的 ,这位大佬空了麻烦帮排查一波

**Comment by jaguarsy** [comment]
暂时只能用在线二维码解码器解码，生成otpauth://totp/xxx@xxx.com?secret=xxxx类似的解码后字符串，拷贝secret后的密钥hash，通过“输入key”的方式提交。
![20180524143722](https://user-images.githubusercontent.com/2453013/40468457-1261d72e-5f60-11e8-84de-32e5d05fec42.png)
